spring:
  application:
    name: ventas

  datasource:
    url: jdbc:postgresql://localhost:5432/ventas_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: soportetiav@gmail.com
    password: tucn dfbu qspk zzki
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
app:
  frontend-url: http://localhost:4200
  upload-dir: ./uploads

server:
  port: 8081

payment:
 terminal:
   type: SIMULATED # O PHYSICAL
   host: 192.168.1.100
   port: 8080
   merchant-id: "MERCHANT12345"
   terminal-id: "TERMINAL001"
   timeout: 30
   ssl-enabled: true
   keystore-path: /certs/terminal.jks
   keystore-password: changeit
   simulation:
    mode: DETERMINISTIC #DETERMINISTIC | RANDOM
    failure-rate: 0.10 #10% de fallos aleatorios
    response-delay: 500 #Delay base en ms